#pragma once

#include <iostream>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>
#include <map>
#include <unordered_map>
#include <set>
#include <unordered_set>
#include <algorithm>
#include <memory>
#include <functional>
#include <thread>
#include <mutex>
#include <chrono>
#include <filesystem>
#include <iomanip>   
#include <limits>    
#include <random>    
#include <utility>   